<?php
/**
 * Implementation of hook_block_info().
 */
function custom_search_block_info() {
  $blocks['custom-search'] = array(
    'info' => t('Custom Search'),
  );
  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function custom_search_block_view($delta='') {
  $block = array();
  switch ($delta) {
    case 'custom-search':
      $block['subject'] = t('Custom search');
      $block['content'] = drupal_get_form('user_custom_search_form');
      break;
  }
  return $block;
}


/**
 * Implementation of hook_menu().
 */

function custom_search_menu(){
 $items = array();
$items['custom_search'] = array(
      'titles'=>t('Game Search'),
	  'page callback'    => 'user_custom_search',
   // 'page arguments'   => array('user_custom_search_form'),
	  'access callback' => TRUE,
      'type' => MENU_CALLBACK,
	  
    );
    return $items;
  }
function user_custom_search(){
$op = '';
$op .= drupal_render(drupal_get_form('user_custom_search_form'));

if(arg(1)!=NULL){
$result = db_query("SELECT * FROM {node} WHERE title LIKE '%".arg(1)."%' AND type = 'game_file'");

$value = array();
foreach($result as $record){
//print "<pre>"; print_r($record); print "</pre>";
//$op .= $record->title."<br>";
global $base_path;
//$op.=' <h2><a href="http://localhost/mrwin/node/'.$record->nid.'" target="_blank" >'.$record->title.'</a></h2>';
$op.=' <h2><a href="'. $base_path.'node/'.$record->nid.'" target="_blank" >'.$record->title.'</a></h2>';
}

/*
//Development Test
$fh = fopen("D:\\temp.txt","a+");
	 ob_start();

     print "<pre>";
	 print_r($value);
	 print "</pre>";
	 print "\n";
	 $end = ob_get_clean();
	 fwrite($fh,$end);
*/

}

$op.="";

return $op;

}

/**
 * Implementation of hook_form().
 */
function user_custom_search_form($form, &$form_state){
 $form['game'] = array(
  '#type' => 'textfield',
  '#title' => t('Search Game Here'),
  '#size' => 25,
  '#maxlength' => 128,
  '#required' => TRUE,
);

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Go'),
	'#submit' => array('custom_search_form_submit'),

  );

 return $form;
}


function custom_search_form_submit($form, &$form_state){
drupal_goto("custom_search/".$form_state['values']['game']);
}

